# Generated by Django 4.2 on 2025-05-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountprofile',
            name='primary_zipcode',
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='primary_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
