# Generated by Django 4.2 on 2025-05-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_county_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='existing_basket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
