# Generated by Django 4.2 on 2025-05-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
    ]
