# Generated by Django 4.2 on 2025-06-15 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_order_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(default=django.utils.timezone.now, max_length=100), # noqa
            preserve_default=False,
        ),
    ]
