# Generated by Django 4.2 on 2025-09-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_slug'),
    ]

    operations = [
    ]
