# Generated by Django 4.2 on 2025-09-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20250926_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used in URLs. Automatically generated from the name if left blank.', max_length=210, unique=True),
        ),
    ]
